steps:
- task: Npm@1
  displayName: 'Install Node dependencies'
  inputs:
    command: install
- powershell: npx tsc -p .
  displayName: 'Run TypeScript type check'
  errorActionPreference: continue
- task: Npm@1
  displayName: 'Run Jest unit tests & Puppeteer UI tests'
  inputs:
    command: test
- task: PublishTestResults@2
  inputs:
    testResultsFiles: junit.xml
- task: PublishBuildArtifacts@1
  displayName: 'Upload screenshots as artifacts'
  inputs:
    pathtoPublish: screenshots
    artifactName: screenshots
