steps:
- task: Npm@1
  displayName: 'Install Node dependencies'
  inputs:
    command: install
- task: Npm@1
  displayName: 'Run Jest unit tests & Puppeteer UI tests'
  inputs:
    command: custom
    verbose: true
    customCommand: test
- task: PublishTestResults@2
  inputs:
    testResultsFiles: junit.xml
- task: PublishBuildArtifacts@1
  displayName: 'Upload screenshots as artifacts'
- powershell: npx tsc -p .
  displayName: 'Run TypeScript type check'
