steps:
- task: Npm@1
  displayName: 'Install Puppeteer & TypeScript'
  inputs:
    command: install
- task: Npm@1
  displayName: 'Run Jest unit tests'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test-wip'
- powershell: npx tsc -p .
  displayName: 'Run type check'
- task: Npm@1
  displayName: 'Run UI tests'
  inputs:
    command: custom
    verbose: false
    customCommand: test
- task: PublishBuildArtifacts@1
  displayName: 'Upload screenshots as artifacts'
  inputs:
    pathtoPublish: screenshots
    artifactName: 'screenshots' 
