steps:
- task: Npm@1
  displayName: 'Install Puppeteer'
  inputs:
    command: install
- task: Npm@1
  displayName: 'Run UI tests'
  inputs:
    command: custom
    verbose: false
    customCommand: test
- task: PublishBuildArtifacts@1
  displayName: 'Upload screenshots as artifacts'
  inputs:
    pathtoPublish: screenshots
    artifactName: 'screenshots' 
