steps:
- task: Npm@1
  displayName: 'Install Puppeteer'
  inputs:
    command: install
- task: Npm@1
  displayName: 'Run UI tests'
  inputs:
    command: custom
    verbose: false
    customCommand: test
